// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwxhyfsiloqgphszjrio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3eGh5ZnNpbG9xZ3Boc3pqcmlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MjExMzYsImV4cCI6MjA2OTQ5NzEzNn0.rrkmqug3XhIfkkYFYapi2tf6ex_VzeK4qDYt78WUaC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});